# Generated by Django 5.2 on 2025-12-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('identificador', models.CharField(db_index=True, max_length=36, unique=True, verbose_name='Identificador')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo_transacao', models.CharField(choices=[('transferencia_pix_enviada', 'Transferência Pix Enviada'), ('transferencia_pix_recebida', 'Transferência Pix Recebida'), ('compra_debito', 'Compra no Débito'), ('recarga_celular', 'Recarga de Celular'), ('pagamento_fatura', 'Pagamento de Fatura'), ('pagamento_boleto', 'Pagamento de Boleto'), ('debito_conta', 'Débito em Conta'), ('outro', 'Outro')], db_index=True, default='outro', max_length=30, verbose_name='Tipo de Transação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Transação Bancária',
                'verbose_name_plural': 'Transações Bancárias',
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['-data', 'tipo_transacao'], name='app_transac_data_5e0d47_idx'), models.Index(fields=['identificador'], name='app_transac_identif_ca7d1d_idx')],
            },
        ),
    ]
