# Generated by Django 5.2 on 2025-12-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transacaobancaria',
            name='app_transac_data_5e0d47_idx',
        ),
        migrations.RemoveField(
            model_name='transacaobancaria',
            name='tipo_transacao',
        ),
    ]
